apiVersion: v1
kind: ConfigMap
metadata:
name: postgres-init
namespace: devops-app
data:
init.sql: |
CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
name VARCHAR(100),
email VARCHAR(100)
);
